### ISSUE TITLE
The problem of barcode prefix

### ISSUE THREAD

**Issue by CCCBBG** [cellgeni/STARsolo#11]
Excuse me.May I have a problem about barcode prefix

This is my bam format
A00582:1096:HGLJCDSX7:2:2346:16179:25003        147     chr1    10001   3       41S108M1S       =    0001    -108    AACCCTAACCATAACCCTAAACACACGTTTAAACCTAACCCTAAACCTAACCCTAACACTAACCCTAACCCTAACCCTAACCCTATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCT   ,,,,,F:,,F,,:F,,:,,,,,,,:,,,,F,F,,,FF:FF,,,FFF,,,FF,,,,:FF,F,FFF,F,F,F::FFFF:,FFF:,FFFFFF:FFFF:F:FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF    NH:i:2  HI:i:1  AS:i:206        nM:i:3  XS:Z:Unassigned_NoFeatures      CB:Z:S001_ATCGATGATGCCC      CR:Z:S001_ATCGATGATGCCTAACC     UB:Z:CTAACCCTAACC       UR:Z:CTAACCCTAACC

I have changed the general bam format such as CB CR
My parameters were
--soloInputSAMattrBarcodeSeq CB UB \
--soloCBwhitelist None \
--soloCBlen 22 \
--soloUMIlen 12 \
--soloFeatures Gene SJ \
--soloBarcodeReadLength 0 \
--soloStrand Reverse

But it seems to be an error
It occurs to me in Log.out that 
Finished reading reads from Solo files nCB=0, nReadPerCBmax=0, nMatch=0

What's going on?
I am looking forward to your reply.Thank you very much

**Comment by apredeus** [comment]
Hi @CCCBBG , 

Unfortunately, I have no idea what are you trying to achieve. This repository is for STARsolo mapping/quantification, which usually starts from fastq files. Are you trying to start from a BAM file? What are you trying to do in general?
