### ISSUE TITLE
Empty output folder

### ISSUE THREAD

**Issue by mhassan** [cellgeni/STARsolo#2]
Hi,
I have tried to run STARsolo on smartseq2 data (~1000 cells) using your starsolo script. The run completes but doesn't produce any files in the output folder. When I ran the script on one cell, I get the necessary files. Is there something I am missing?

**Comment by apredeus** [comment]
Hi Hassan, 

It's a bit hard to debug this without seeing the files. Could you message me or make a Jira ticket for it? Thanks!
