### ISSUE TITLE
Can I use the STARsolo for the multiome data?

### ISSUE THREAD

**Issue by kkonoo** [cellgeni/STARsolo#6]
Hi there,

I have overloaded multiome data (with >20k cells), so I don't want to use cell ranger arc, which has a limit in the number of cells to be called.
Can I use the STARsolo for the multiome data?
If so, how can I use it?

Best,
E

**Comment by apredeus** [comment]
Hi E, 
I don't think you can do ATAC-seq processing with STARsolo (even in Cell Ranger they use `bwa` + `macs2` to map the genomic reads and call peaks). But if you're only interested in the RNA part of the multiome, then a normal 10x workflow (and using _GeneFull_ output) should work well.
